export const GET_USERS= "GET_USERS";
export const START_USERS_LOADING = "START_USERS_LOADING";
export const FINISH_USERS_LOADING = "FINISH_USERS_LOADING";
export const GET_POSITIONS = "GET_POSITIONS";
export const SIGN_UP = "SIGN_UP";


export const SHOW_MESSAGE = "SHOW_MESSAGE"; 
export const HIDE_MESSAGE = "HIDE_MESSAGE";