export const GET_USERS= "GET_USERS";
export const CLEAR_USERS_DATA = "CLEAR_USERS_DATA";
export const START_USERS_LOADING = "START_USERS_LOADING";
export const END_USERS_LOADING = "END_USERS_LOADING";
export const GET_POSITIONS = "GET_POSITIONS";
export const SIGN_UP = "SIGN_UP";
export const START_SIGN_UP_PROCESSING = "START_SIGN_UP_PROCESSING";
export const END_SIGN_UP_PROCESSING = "END_SIGN_UP_PROCESSING";

export const SHOW_MESSAGE = "SHOW_MESSAGE"; 
export const HIDE_MESSAGE = "HIDE_MESSAGE";